extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:

  opencensus:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  batch:
  queued_retry:
  groupbytrace:

exporters:
  logging:
    logLevel: debug
  datadog:
    api_key: 123
    api_url: test
    sample_rate: 1
    debug: false

service:

  pipelines:

    traces:
      receivers: [opencensus, jaeger, zipkin]
      processors: [groupbytrace, batch]
      exporters: [datadog]

    # metrics:
    #   receivers: [opencensus, prometheus]
    #   processors: [batch]
    #   exporters: [logging]

  # extensions: [health_check, pprof, zpages]
